run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number  # Changed from formats array to single format
  print-issued-lines: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - gosimple
    - goconst
    - goimports
    - unused
    - misspell
    - revive

linters-settings:
  govet:
    check-shadowing: true  # Enable shadow checking in govet
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  max-same-issues: 3
  
  exclude-dirs:
    - vendor
    
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec