apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-v2-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Service V2</title>
    </head>
    <body>
        <h1>Version 2 of the service</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
      version: v2
  template:
    metadata:
      labels:
        app: service1
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: config-volume
        configMap:
          name: nginx-v2-config
---
apiVersion: v1
kind: Service
metadata:
  name: service1-v2
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: service1
    version: v2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service1-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  ingressClassName: nginx
  rules:
  - host: app1.test
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: service1-v2
            port:
              number: 80