apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-v1-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Service V1</title>
    </head>
    <body>
        <h1>Version 1 of the service</h1>
        <p>This is the stable version</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service1
      version: v1
  template:
    metadata:
      labels:
        app: service1
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: config-volume
        configMap:
          name: nginx-v1-config
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: service1
    version: v1